/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FixedLinks: typeof import('./src/components/FixedLinks.vue')['default']
    NotFound: typeof import('./src/components/NotFound.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Welcome: typeof import('./src/components/Welcome.vue')['default']
  }
}
